import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
function ToolCard({ title, description, icon, onClick, disabled }) {
    return (_jsxs("button", { onClick: onClick, disabled: disabled, className: `text-left bg-white rounded-xl shadow-md p-6 border border-gray-100 transition-all
        ${disabled
            ? 'opacity-50 cursor-not-allowed'
            : 'hover:shadow-lg hover:-translate-y-0.5 cursor-pointer'}`, children: [_jsx("div", { className: "w-12 h-12 rounded-lg bg-leve-blue bg-opacity-10 flex items-center justify-center mb-4 text-leve-blue", children: icon }), _jsx("h3", { className: "text-base font-bold text-gray-800 mb-1", children: title }), _jsx("p", { className: "text-sm text-gray-500", children: description }), disabled && (_jsx("span", { className: "inline-block mt-3 text-xs font-semibold text-gray-400 bg-gray-100 px-2 py-1 rounded", children: "Em breve" }))] }));
}
export default function Dashboard({ onSelectTool }) {
    return (_jsxs("div", { className: "max-w-7xl mx-auto p-6", children: [_jsx("h1", { className: "text-xl font-bold text-gray-800 mb-1", children: "Ferramentas do Setor" }), _jsx("p", { className: "text-sm text-gray-500 mb-6", children: "Selecione uma ferramenta para come\u00E7ar" }), _jsxs("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5", children: [_jsx(ToolCard, { title: "Gerador de Selos", description: "Gere selos de libera\u00E7\u00E3o a partir de uma lista de c\u00F3digos em TXT, com c\u00F3digo de barras e exporta\u00E7\u00E3o em PDF.", onClick: () => onSelectTool('selos'), icon: _jsx("svg", { className: "w-6 h-6", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" }) }) }), _jsx(ToolCard, { title: "Carta de Suspens\u00E3o Disciplinar", description: "Preencha os dados do funcion\u00E1rio e da ocorr\u00EAncia e exporte a carta de suspens\u00E3o pronta para assinatura.", onClick: () => onSelectTool('suspensao'), icon: _jsx("svg", { className: "w-6 h-6", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" }) }) }), _jsx(ToolCard, { title: "Mais ferramentas", description: "Novas ferramentas do setor de auditoria ser\u00E3o adicionadas aqui.", onClick: () => { }, disabled: true, icon: _jsx("svg", { className: "w-6 h-6", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M12 4v16m8-8H4" }) }) })] })] }));
}
